import { Component } from '@angular/core';

function log(className) {
  console.log(className);
  return (...args) => {
    console.log('Arguments passed to this class\'s constructor are ', args);
    return new className(...args);
  };
}
@log
class MyExampleClass {
  constructor(arg1, arg2) {
    console.log('Constructor fired');
  }
}

const myClass = new MyExampleClass(5, 18);

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})

export class AppComponent {
  title = 'app';

  constructor() {
    console.log('this statement was generated by the constructor ', this.aSimpleMethod(5, 2));
  }

  aSimpleMethod(a, b) {
    return a * b;
  }
}
